version: '3.9'
volumes:
  node_modules:
services:
  db:
    container_name: postgres
    image: postgres:16.2-bookworm
    restart: unless-stopped
    shm_size: 256mb
    volumes:
      - ./.db/init.sql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PWD}
    ports:
      - 5432:5432

  link-shortener:
    container_name: linkShortener
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        node_env: development
      tags:
        - cristobaldominguez/linkshortener:1.0.0
      platforms:
        - "linux/arm64"
        - "linux/amd64"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - db
    ports:
      - 3000:3000
    command: ["node", "--watch", "server.js"]
